### ISSUE TITLE
Figure out how to test chart.js (sandbox)

### ISSUE THREAD

**Issue by david-gauquelin** [vojtechsimetka/planuj.finance#143]

**Comment by vojtechsimetka** [comment]
- Sandbox: https://quickchart.io/sandbox
- Config: https://www.chartjs.org/docs/latest/configuration/
- Codepen: https://codepen.io/vojtechsimetka/pen/NWmyPbw?editors=0010
- Figma: https://www.figma.com/community/file/1111335120507995139/chartjs-responsive-graphs-pie-bar-line-doughnut-radar-multitype-graph-for-js-library
