### ISSUE TITLE
Advisor's Fee View

### ISSUE THREAD

**Issue by nikpage** [vojtechsimetka/planuj.finance#192]
As an advisor I want a view of client portfolios that includes my fees so I can plan my advice prior to the client meeting.

I want this to be per client portfolio and my aggregate expected receipts (monthly / quarterly/ annual) 

NOTE: It needs to be done in a way that make accidental client viewing very unlikely :-)

**Comment by vojtechsimetka** [comment]
We don't do this because the data is not available for most of the advisors and the fee structure is often multi-level.
