### ISSUE TITLE
Login and Signup screens

### ISSUE THREAD

**Issue by vojtechsimetka** [vojtechsimetka/planuj.finance#216]
Currently we have temporary ones looking like this:

![Screenshot 2024-08-26 at 17 00 16](https://github.com/user-attachments/assets/e2fdf5d8-7738-4bde-b587-310cd93aa458)

![Screenshot 2024-08-26 at 17 00 24](https://github.com/user-attachments/assets/fcfa1da8-b054-4e08-b4b7-71bb4a24f55e)

**Comment by david-gauquelin** [comment]
Shouldn't we have a forgot password link? How do we deal with forgotten passwords?

**Comment by david-gauquelin** [comment]
<img width="1440" alt="login" src="https://github.com/user-attachments/assets/2e7e6c63-0e24-4d22-83d7-a81e5fc38f7b">
<img width="1440" alt="signup" src="https://github.com/user-attachments/assets/c1451456-8b2a-4b74-916e-336803e75b8a">

**Comment by agazso** [comment]
> Shouldn't we have a forgot password link? How do we deal with forgotten passwords?

Yes, we should have a forgot password link. It should reset the password and send an email with a link so that you can enter the new password.

**Comment by agazso** [comment]
Implemented in #231
